---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(lubridate); library(stringr); library(dplyr); library(readr); library(purrr)
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
names(invoiceList)[[2]] <- "訂單時區之下單時間"
invoiceList
```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$UTC時間[nyLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York"),tzone="UTC")
invoiceList$UTC時間[tpLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei"),tzone="UTC")

invoiceList 
```

```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],
        tz="America/New_York") -> nyDateTime

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],
        tz="Asia/Taipei") -> tpDateTime

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```

```{r}
library(lubridate)
a <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
timez1 <-with_tz(a, tz="Asia/Taipei")

ymd_hms_tzChange <- function(x,y,z){
  a <- ymd_hms(x,tz=y)
  timez1 <-with_tz(a, tzone = z)
  return(timez1)
}
```

```{r}
#錯誤

ymd_hms_tzChange <- function(date, TZ1, TZ2){
  nyDT2 <- ymd_hms("1973-02-21 12:05:22", tz=TZ1)
  tpDT2 <- with_tz(nyDT2, tz=TZ2)
  return(tpDT2)
  }
#更正

ymd_hms_tzChange <- function(date, TZ1, TZ2){
  nyDT2 <- ymd_hms(date, tz=TZ1)
  tpDT2 <- with_tz(nyDT2, tzone=TZ2)
  return(tpDT2)
  }
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```

```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```

```{r}
date_convert_twYM <- function(x){
  library(stringr); library(lubridate)
  yyyy <-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
  mm <-str_extract(x,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  ans <- ymd(yyyymmdd)
  return(ans)
}
```

#預設
```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```

```{r}
date_convert_twYM <- function(x,day1="01"){
  library(stringr); library(lubridate)
  yyyy <-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
  mm <-str_extract(x,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,day1,sep="-"))
  ans <- ymd(yyyymmdd)
  return(ans)
}
date_convert_twYM(twDates,"02")
```

