---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(.beta=0.8,1,.alpha=0.5,2)
```

#迴圈
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```


```{r}
gpa_fun(transcriptDataFinal$學號)
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
# 以前5筆學號為sequence_source
```

#作法一
```{r}
studentIds5 <- studentIds[1:5]
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```

#作法二
```{r}
for(i in c(1:5)){
  print(i) 
}
for(i in c(1:5)){
  print(studentIds5[[i]]) # 
}
```

#作法三c()改用seq_along()
```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

#練習二
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

#作法一
```{r}
for(i in gmailAddress){
  print(i) # 印出studentIds5[[i]]
}
```

#作法二
```{r}
for(i in c(1:4)){
  print(i) 
}
for(i in c(1:4)){
  print(gmailAddress[[i]]) # 
}
```

#作法三
```{r}
for(i in seq_along(gmailAddress)){
  print(gmailAddress[[i]])
}
```

