---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#2019-04-03 class
#review
```{r}
x3 <- c("小明", "小花")
y3 <- c("小明", "小華")

x3 == y3
x3 != y3
!( x3 == y3 )
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
```{r}
head(currency)
```

```{r}
class(currency)
```

#將currency改成factor class
```{r}
currency <- as.factor(currency)
class(currency)
```

```{r}
levels(currency)
```
#length():屬向量內的元素個素
```{r}
length(levels(currency))
```
#有幾個日圓
```{r}
currency == "日圓JPY/USD"
sum(currency == "日圓JPY/USD")
```

#邏輯練習
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

#交集
```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) & (y5=="女")
```

```{r}
which((x5 %in% greatTaipei) & (y5=="女"))
```

#聯集
```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) | (y5=="女")
```

#反交集(兩個只有一個滿足)
```{r}
x5 %in% greatTaipei
y5=="女"
xor(x5 %in% greatTaipei, y5=="女")
!((x5 %in% greatTaipei) & (y5=="女"))
```

```{r}
which(xor(x5 %in% greatTaipei, y5=="女"))
```

#綜合練習
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
#1
```{r}
class(date)
```
```{r}
head(date)
```

```{r}
library(lubridate)
date <- ymd(date)
```

```{r}
class(date)
```

#2
```{r}
isAfter19800801 <- 
  date >= ymd("1980-08-01")
isAfter19800801
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```

```{r}
class(isAfter19800801)
sum(isAfter19800801)
```

#3
```{r}
head(currency)
```

```{r}
head(currency == "歐元USD/EUR")
isEURO <- currency == "歐元USD/EUR"
```

```{r}
sum(isEURO)
```

#有將currency轉成factor
```{r}
currency <- as.factor(currency)
isEURO <- currency == "歐元USD/EUR"
sum(isEURO)
```

#4
```{r}
isExchangeRateNA <-
  is.na(exchangeRate)
sum(isExchangeRateNA)
```

#5
```{r}
isNotNA <- !isExchangeRateNA
isEURO <- currency == "歐元USD/EUR"

satisfyBoth <- isNotNA & isEURO
sum(satisfyBoth)
```


#另一題
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```


#1
```{r}
sum(major == "經濟學系")
```

#2
```{r}
sum(studentID == "5bdS6977b")
```

#3
```{r}
sum(
  studentID == "5bdS6977b" &
  grade >= 60
)
```

#4
```{r}
sum(
  major == "經濟學系" &
    courseType == "選"
)
```

#5
```{r}
sum(
  major == "經濟學系" &
    courseType == "必"
) -> mom
mom
```
```{r}
sum(
  major == "經濟學系" &
    courseType == "必" &
      grade < 60
) -> kid
kid
```
```{r}
kid/mom
```


