---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#dataframe colname/rownames
```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
StuDF2
```

```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
StuDF2
```

```{r}
rownames(StuDF2) <- c("a","b","c","d","e")
StuDF2
rownames(StuDF2)[c(1,2,3)] <- c("A","B","C")
StuDF2
```

#新增/取代
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b[[3]] <- FALSE #(b$元素3 <- FALSE)
b[[5]] <- 7
b[["元素4"]] <- c(1,2,3)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
exData3
```
#第一題
```{r}
library(lubridate)
exData3[[1]] <- ymd(exData3[[1]])
class(exData3[[1]])
```
#第二題
```{r}
time1 <- ymd("1997-06-01")
time2 <- ymd("1998-12-01")
exData3$isAsiaCrisis <- (exData3[[1]] >= time1 & exData3[[1]] <= time2)
class(exData3$isAsiaCrisis)
```
#第三題
```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]
#exData3[exData3$isAsiaCrisis==T ,]
#exData3[exData3$isAsiaCrisis,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

#找單一學生的資料
```{r}
ID <- "92aS67fee"
transcriptDataFinal$學號 == ID -> ID1
transcriptDataFinal [ID1,] 
```

#算GPA
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```

```{r}
studentID <-"92aS67fee" 
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
gpa_fun(studentID) # 使用global environmen裡物件studentID的值當輸入值
gpa_fun("92aS67fee")
```


```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
num <- function(x,.alpha){
  num1 <- x+.alpha # 程序產生output值
  return(num1) # 傳回output值
}
num(2,4)
```

```{r}
supply_fun <- function(a,b,P){
  Qs <- a+b*P
  return(Qs)}
demand_fun <- function(c,d,P){
  Qd <- c-d*P
  return(Qd)
}
class(supply_fun)
supply_fun(0,1,1)
demand_fun(5,1,1)
```

