---
title: '2000-03-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Date
```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)

dtObject
typeof(dtObject)
as.integer(dtObject)
as.double(dtObject)
```

#Date Practice
```{r}
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime

typeof(twDateTime)
as.double(twDateTime)
typeof(LisbonDateTime)
as.double(LisbonDateTime)
```


```{r}
library(lubridate)
dt1object <- mdy_hms("3/14/2019 08:18:47", tz="Asia/Taipei")
dt1bjectVector<-mdy_hms(
  c("3/14/2019 08:18:47",
    "3/14/2019 08:18:47")
)

dt1object
```

```{r}
library(lubridate)
testdatetime1 <- ymd("2018-09-11")
testdatetime1

testdatetime2 <- mdy("March 3, 2019")
testdatetime2
```

```{r}
as.integer (ymd("1970-01-01"))
as.integer (ymd("1970-01-02"))
as.integer (ymd("2019-03-11"))
```

#math
```{r}
a <- c(1, 5, -3)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+bL
aL+bL
a-bL
aL-bL
a*bL
aL*bL
a/bL
aL/bL

c <- 4
c+a

class(a)
class(aL)

a^bL
a %% bL
```

#datemath
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime +1
twDateTime +15972
twDateTime2 <- ymd_hms("2019-03-18 18:30:12", tz="Asia/Taipei")

twDateTime2 - twDateTime
class(twDateTime2 - twDateTime)
as.integer(twDateTime2 - twDateTime)
as.numeric(twDateTime2 - twDateTime)
as.difftime(twDateTime2 - twDateTime)
```

#operatedate
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)

ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

#code
```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,y,20)

x3 <- c("小明","小花")
y3 <- c("小明","小華")
x2 == y2
x3 != y3
x == y
x = y
x == y
x == y2
```

#belong
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)
x4 %in% y4

x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")
x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
x2 == y2
x3 == y3

is.na(x2)
is.na(y2)
is.na(y3)

sum(x2)
sum(x2,na.rm=F)
sum(x2,na.rm = TRUE)
```



