---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )
studentRecord
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

#[[.]]取出括號內一個的元素(取出來的是charactor)
```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
plasticContainer[["redBox"]] 
```

```{r}
plasticContainer[["greenBox"]] [[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[[1]]
```

```{r}
studentRecord[[2]]
studentRecord[[4]][[3]]
```

#[.,.]取出括號內的多個元素=>保有原來的class(取出來的是list)
```{r}
classa <- plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
class(classa)
```

```{r}
extract1 <- plasticContainer[c("greenBox")]
extract1
class(extract1)
extract2 <- plasticContainer[[c("greenBox")]]
extract2
class(extract2)
```

```{r}
extract1[[1]][[1]]
extract2[[1]]
```

```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
成績單
成績單[c(TRUE,TRUE,FALSE)]
```

```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

#看自己的出席
```{r}
your_github_username <- "roderick11"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
commitCheckStatement

```

#6.4.6 ` `=>名稱很機車要把它刮起來
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp

```

```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```

```{r}
logiCorrect <- str_length(birthday) == 8
logiCorrect
class(logiCorrect)
```
```{r}
favoriteTwo[logiCorrect] -> ValidFavorYwo
ValidFavorYwo
class(favoriteTwo)
```
```{r}

```

